In [15]:
import numpy as np

In [20]:

list_of_items=[23,45,67,89,90]
list_of_items_2=[23,45,82,30,2]

In [17]:
#these are single dimensional arrays
items = np.array([23,45,67,89,90])
items_2 = np.array([23,45,82,30,2])

In [18]:
items

array([23, 45, 67, 89, 90])

In [19]:
items_2

array([23, 45, 82, 30,  2])

In [21]:
type(items)

numpy.ndarray

In [22]:
type(list_of_items)

list

In [23]:
items*items_2

array([ 529, 2025, 5494, 2670,  180])

In [25]:
# Knowing the size of a numpy array

items.size

5

In [26]:
#Knowing the shape of of a Numpy array
#5 columns and no rows 
items.shape

(5,)

In [30]:
items.ndim

1

In [28]:
#2 dimensional arrays

items_3 = np.array([[23,45,67,89,90], [23,45,67,89,90]])

In [29]:
items_3.shape
#2 rows and 5 columns 

(2, 5)

In [31]:
#you always have to square everything off with outer sqaure brackets
#3-dimensional arrays 
items_4 = np.array([[[23,45,67,89,90], [23,45,67,89,90]],[[23,45,7,89,90], [23,45,7,89,90]]])

In [32]:
items_4.shape

(2, 2, 5)

In [34]:
items_4.ndim

3

In [36]:
#Accessing items within ndarrays 
#starting with single dimensional arrays
items = np.array([23,45,67,89,90])
#index position 0
items[0]

23

In [37]:
#negative indexing 
items[-1]

90

In [38]:
#2 dimensional arrays items_3
items_3[0,1]


45

In [41]:
items_30=np.array([[23,45,4],[20,43,4]])

In [42]:
items_30[1,0]

20

In [43]:
items_30[1,-1]

4

In [44]:
[items_30[1,0],items_30[1,-1]]

[20, 4]

In [46]:
np.array([[items_30[1,0],items_30[1,-1]]])

array([[20,  4]])

In [47]:
items_30[1,[0,2]]

array([20,  4])

In [48]:
items_30[[1,0],[1,2]]

array([43,  4])

In [57]:
#Accessing items from 3-dimensional arrays 
items_40=np.array([[[23,45,4],[23,45,4]],[[3,5,4],[23,5,4]]])

In [58]:
items_40

array([[[23, 45,  4],
        [23, 45,  4]],

       [[ 3,  5,  4],
        [23,  5,  4]]])

In [59]:
items_40[1,0,0]

3

In [67]:
# : means all items - accessing everything in that row level 
print(items_40[0:,0:,1])
print(items_40[:,:,1])

[[45 45]
 [ 5  5]]
[[45 45]
 [ 5  5]]


In [65]:
#showing the last two numbers in each one 
items_40[0:,0:,[1,2]]

array([[[45,  4],
        [45,  4]],

       [[ 5,  4],
        [ 5,  4]]])

In [69]:
items_40[0,:,1]

array([45, 45])

In [70]:
#Changing items within arrays 
#Change 45 to 5
items

array([23, 45, 67, 89, 90])

In [71]:
items[1]=5

In [72]:
print(items)

[23  5 67 89 90]


In [73]:
items

array([23,  5, 67, 89, 90])

In [74]:
#Chnging multiple items within the arrays 
items_4

array([[[23, 45, 67, 89, 90],
        [23, 45, 67, 89, 90]],

       [[23, 45,  7, 89, 90],
        [23, 45,  7, 89, 90]]])

In [76]:
#Change all the items in the middle columns to 8,9,10,11
items_4[:,:,2]=[[8,9],[10,11]]

In [77]:
items_4

array([[[23, 45,  8, 89, 90],
        [23, 45,  9, 89, 90]],

       [[23, 45, 10, 89, 90],
        [23, 45, 11, 89, 90]]])